# -*- coding: utf-8 -*-
"""
Created on Tue Sep 10 10:29:27 2013

@author: kundlj
"""

from os.path import isfile

def process_file(filename):
    """ Processes a single GoNoGo file generated by the LRC's GoNoGo reation
        game. filename is the name of the .txt file. """
        
    if not isfile(filename):
        return
    
    info = [x.strip('.txt') for x in filename.split('_')]
    
    subject = info[1][8:]
    session = info[2][8:]
    trial = info[3][6:]
    
    with open(filename, 'r') as filepointer:
        data = filepointer.readlines()
    
    data = [x.strip('\n').split(' ') for x in data]
    
    valid = []
    hit = miss = no_reaction = false_pos = false_alarm = 0.0
    
    for item in data:
        if len(item) < 2:
            false_alarm += 1
            continue
        else:
            time = int(item[0])
            color = item[1]
        
        if color == 'A' and time <= 1000:
            hit += 1
            valid.append(time)
            
        elif color == 'A' and time > 1000:
            miss += 1
            
        elif color == 'B' and time > 1000:
            no_reaction += 1
            
        elif color == 'B' and time <= 1000:
            false_pos += 1
            
    valid.sort()

    valid_median = valid[len(valid)/2]
    valid_mean = sum(valid)/len(valid)
    
    percent_missed = float(miss/(miss + hit) * 100)
    
    percent_false = float(false_pos/(false_pos + no_reaction) * 100)
    
    error_rate = float((miss + false_pos + false_alarm) / len(data))
    
    ten_percent = len(valid)/10
    switch = ten_percent/2
    
    top_median = valid[len(valid) - ten_percent + switch]
    top_mean = sum(valid[len(valid) - ten_percent:])/ten_percent
    
    bottom_median = valid[switch]
    bottom_mean = sum(valid[:ten_percent])/ten_percent
    
    top_thruput = float((100 * (hit + no_reaction)/len(data))/top_median)
    bottom_thruput = float((100 * (hit + no_reaction)/len(data))/bottom_median)
        
    return [[subject, session, trial], [valid_median, valid_mean, \
            percent_missed, percent_false, error_rate, top_median, top_mean, \
            bottom_median, bottom_mean, top_thruput, bottom_thruput]]
    